### ISSUE TITLE
Change CoPilot TRP Export so all route points are Waypoints.

### ISSUE THREAD

**Issue by allthingssatnav** [furkot/furkot-copilot#2]
As best I can determine the following is an appropriate format:

Start Stop=Stop (n)
Name=
Address=
City=
State=
County=
Zip=
Longitude=
Latitude=
Show=1
Sequence=(n)
End Stop

I have not figured out what parameter CoPilot uses in deciding which Stop to make the Route segment End point before showing the next segment in the Route.  I think if CoPilot users (like me) want to have just a few Stops then they should make sure they have their Furkot Plan using mostly Pass-through's with only a few Stops.

**Comment by melitele** [comment]
CoPilot Stop = Furkot regular (i.e. duration > 0) stop:

Show=1

CoPilot Waypoint = Furkot pass-through point / extra route point (when "routes" option is set):

Show=0

The above mapping of Furkot stops/pass-through's should hold regardless of the "routes" option.

Furkot pass-through points should always export as CoPilot waypoints (Stop=0). Oftentimes they export  as CoPilot stops (Stop=1) and it's a bug. I am going to fix it.

**Comment by allthingssatnav** [comment]
As of this my Export this morning, all route points are being exported as set to Show=1 regardless of using the Route option at Export.

**Comment by allthingssatnav** [comment]
When using the Routes Option and appending points to the route, the points added are set to Show=0: as they should be.

**Comment by melitele** [comment]
I am going to fix CoPilot export so pass-through points always export as CoPilot waypoints (Stop=0) regardless of the Routes Option.

**Comment by allthingssatnav** [comment]
Excellent.

**Comment by melitele** [comment]
fixed
